[package]
name = "hdf5"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
memmap = "0.7"
nom = {version = "5.0", default-features = false, features = ["std"]}
